name: Build and deploy ASP.Net Core app to Azure Web App - IoTDataPortal-Api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout
      id-token: write # Required for azure/login

    steps:
      # 1. HÃ¤mta koden
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup .NET 10
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      # 3. Bygg projektet
      - name: Build project
        run: dotnet build backend/IoTDataPortal.API/IoTDataPortal.API.csproj --configuration Release

      # 4. Publicera projektet
      - name: Publish project
        run: dotnet publish backend/IoTDataPortal.API/IoTDataPortal.API.csproj -c Release -o ./publish

      # 5. Login till Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_612A5293451D4CFAA18A4E816E3AECFB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D37DB4891EEA4D549582221FDBC9866A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F4C09FC9A587480385344ECAE6557A87 }}

      # 6. Deploy till Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'IoTDataPortal-Api'
          slot-name: 'Production'
          package: ./publish
